### ISSUE TITLE
Indexing fails when triggered from a background job

### ISSUE THREAD

**Issue by iliyan-kulishev** [skttl/umbraco-fulltextsearch8#122]
I have a background job in my Umbraco solution that is supposed to publish content pages in bulk with the expectation that FullTextSearch re-index them.

![image](https://github.com/skttl/umbraco-fulltextsearch8/assets/22516081/0975a8d0-2b5b-4572-b2f4-812de6e8c73f)

But what happens is this (from the Umbraco logs)

![image](https://github.com/skttl/umbraco-fulltextsearch8/assets/22516081/37032cd4-a6a7-4ad0-b976-2ec7395be3db)

The indexing of the page in question fails with SocketException when the HttpPageRenderer in FullTextSearch tries to make a request to a controller for the page HTML.

What could be the reason for that ?

**Comment by skttl** [comment]
Is it only when triggered by your background task? The error message suggests, that it can't make the HTTP request for rendering the page.

**Comment by kows** [comment]
@skttl 
we are experiencing this issue when a page is published via schedule.
Manual publish does not throw this.

**Comment by skttl** [comment]
Hi @kows

Can you add some more info, eg. log message, stack trace, version (both Umbraco and Full Text Search)?

**Comment by kows** [comment]
Umbraco version 13.5.0
Fulltext version 4.0.2.0 
and also  Umbraco 13.6.0 with Fulltext 4.1.0.0


Error in http-request for full text indexing of page 1234, tried to fetch "http://localhost/xxx/xxxxxx/"
```
System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissions. (localhost:80)
 ---> System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Our.Umbraco.FullTextSearch.Rendering.HttpPageRenderer.Render(IPublishedContent publishedContent, PublishedCultureInfo culture)
```

**Comment by skttl** [comment]
Looks like #126
