### ISSUE TITLE
FullTextCache table nullReferenceExceptions

### ISSUE THREAD

**Issue by Sven883** [skttl/umbraco-fulltextsearch8#124]
Hello!

We're using umbraco v8.14.1 with fulltextsearch v1.3.0.
We notice that our dbo.FullTextCache table is full with the following rows (+- 1800 of 2843 total rows):

 ```
System.NullReferenceException: Object reference not set to an instance of an object.
at LightInject.Web.PerWebRequestScopeManager.GetOrAddScope() in C:\projects\lightinject-web\build\tmp\Net46\Binary\LightInject.Web\LightInject.Web.cs:line 148
at DynamicMethod(Object[] )
at Umbraco.Web.Mvc.ContainerControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType) in D:\a\1\s\src\Umbraco.Web\Mvc\ContainerControllerFactory.cs:line 21
--- End of inner exception stack trace ---
at Umbraco.Web.Mvc.ContainerControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType) in D:\a\1\s\src\Umbraco.Web\Mvc\ContainerControllerFactory.cs:line 25
at Umbraco.Web.Mvc.UmbracoControllerFactory.CreateController(RequestContext requestContext, String controllerName) in D:\a\1\s\src\Umbraco.Web\Mvc\UmbracoControllerFactory.cs:line 38
at Umbraco.Web.Mvc.RenderControllerFactory.CreateController(RequestContext requestContext, String controllerName) in D:\a\1\s\src\Umbraco.Web\Mvc\RenderControllerFactory.cs:line 36
at System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController& controller, IControllerFactory& factory)
at System.Web.Mvc.MvcHandler.ProcessRequest(HttpContextBase httpContext)
at Umbraco.Web.Templates.TemplateRenderer.RenderUmbracoRequestToString(RequestContext requestContext) in D:\a\1\s\src\Umbraco.Web\Templates\TemplateRenderer.cs:line 169
at Umbraco.Web.Templates.TemplateRenderer.ExecuteTemplateRendering(TextWriter sw, PublishedRequest request) in D:\a\1\s\src\Umbraco.Web\Templates\TemplateRenderer.cs:line 139
at Umbraco.Web.Templates.TemplateRenderer.Render(Int32 pageId, Nullable`1 altTemplateId, StringWriter writer) in D:\a\1\s\src\Umbraco.Web\Templates\TemplateRenderer.cs:line 108
at Umbraco.Web.UmbracoComponentRenderer.RenderTemplate(Int32 contentId, Nullable`1 altTemplateId) in D:\a\1\s\src\Umbraco.Web\UmbracoComponentRenderer.cs:line 52' --> 
```

Does this have any impact on the performance of this package?
Maybe this is related to https://github.com/skttl/umbraco-fulltextsearch8/issues/77? 

Would be greatly appreciated if you could take a look at this please! :-)

**Comment by skttl** [comment]
Fixed in v4 with the http renderer, sorry.

Not going to do anymore for earlier versions.

**Comment by Sven883** [comment]
@skttl understandable! But could you tell us if this has any impact on the performance of search queries please?

**Comment by skttl** [comment]
It shouldn't
