### ISSUE TITLE
JSON deserialize error with `Umbraco.Cms.Core.RichTextEditorValue`

### ISSUE THREAD

**Issue by timeverts** [skttl/umbraco-fulltextsearch8#125]
Hi,

Love this plugin btw! Thanks for all your work.

I'm doing a reindex on an Umbraco 13.1.1 website and while reindexing, the following exception is being thrown in the background console:
```
 Could not parse rich text editor value, see exception for details.
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Umbraco.Cms.Core.RichTextEditorValue' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Umbraco.Cms.Core.PropertyEditors.RichTextPropertyEditorHelper.TryParseRichTextEditorValue(Object value, IJsonSerializer jsonSerializer, ILogger logger, RichTextEditorValue& richTextEditorValue)
```

Unfortunately it's not very descriptive as to what exactly is causing the error (e.g. a particular field id or handle).
Any ideas on what I can do to narrow down or resolve the issue?

Thanks.

**Comment by skttl** [comment]
Are you sure full text search is the cause of this? Don't see it mentioned in the stack trace.

**Comment by timeverts** [comment]
I realize full text plugin isn't mentioned, but it seems to happen every time we reindex.
We can investigate further.
