### ISSUE TITLE
Error when rendering template

### ISSUE THREAD

**Issue by lumimario** [skttl/umbraco-fulltextsearch8#133]
I have configured Full Text Search to use `RazorPageRenderer` and it's working fne in local. The problem is that in an Azure Webapp I'm getting an exception:

```
FullTextSearch: Error updating nodeId: 11409 in culture:  using templateId: 3589: <!-- Error rendering template with id 11409: 'System.InvalidOperationException: HttpContext is null

   at Umbraco.Extensions.HttpContextAccessorExtensions.GetRequiredHttpContext(IHttpContextAccessor httpContextAccessor)

   at Umbraco.Cms.Web.Common.Templates.TemplateRenderer.ExecuteTemplateRendering(TextWriter sw, IPublishedRequest request)

   at Umbraco.Cms.Web.Common.Templates.TemplateRenderer.RenderAsync(Int32 pageId, Nullable`1 altTemplateId, StringWriter writer)

   at Umbraco.Cms.Core.Templates.UmbracoComponentRenderer.RenderTemplateAsync(Int32 contentId, Nullable`1 altTemplateId)' -->
 ```

Any ideas of how to fix this?

Thank you.

**Comment by lumimario** [comment]
This was happening in a load balanced setup. The public site was also indexing the content. I fixed by disabling indexing in the public site.

**Comment by skttl** [comment]
Cool, thanks for getting back!

Any chance you could do a PR for the docs with a note regarding load balancing? :)

**Comment by lumimario** [comment]
Sure thing! Thanks for the package BTW, it's great.
